from django.urls import path
from . import views
from . import library_views

urlpatterns = [
    path('', views.index_page, name='index'),
        path('register/', views.register, name='register'),
    path('dashboard/register/', views.admin_register_student, name='admin_register_student'),
    path('dashboard/student-details/<int:student_id>/', views.student_details, name='student_details'),
    path('dashboard/approve-student/<int:student_id>/', views.approve_student, name='approve_student'),
    path('dashboard/reject-student/<int:student_id>/', views.reject_student, name='reject_student'),
    path('dashboard/delete-student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('dashboard/update-student/<int:student_id>/', views.update_student, name='update_student'),
    path('student_status/', views.student_status, name='student_status'),
    path('change-password/', views.change_student_password, name='change_student_password'),
        path('logout/', views.logout_view, name='logout'),
    path('login/', views.login_view, name='login'),
    path('forgot-password/', views.forgot_password, name='forgot_password'),
    path('reset-password/<uuid:token>/', views.reset_password, name='reset_password'),
    path('teacher/', views.teacher_view, name='teacher'),
        path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    # Teacher Management URLs
    path('dashboard/add-teacher/', views.add_teacher, name='add_teacher'),
    path('dashboard/get-teachers/', views.get_teachers, name='get_teachers'),
    path('dashboard/delete-teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    # Session Management URLs
    path('dashboard/add-session/', views.add_session, name='add_session'),
    path('dashboard/get-sessions/', views.get_sessions, name='get_sessions'),
    path('dashboard/update-session/<int:session_id>/', views.update_session_status, name='update_session_status'),
    path('dashboard/delete-session/<int:session_id>/', views.delete_session, name='delete_session'),
    # Subject Management URLs
    path('dashboard/add-subject/', views.add_subject, name='add_subject'),
    path('dashboard/get-subjects/', views.get_subjects, name='get_subjects'),
    path('dashboard/update-subject/<int:subject_id>/', views.update_subject_status, name='update_subject_status'),
    path('dashboard/delete-subject/<int:subject_id>/', views.delete_subject, name='delete_subject'),
    path('dashboard/get-courses-dropdown/', views.get_courses_for_dropdown, name='get_courses_for_dropdown'),
    path('dashboard/get-teachers-dropdown/', views.get_teachers_for_dropdown, name='get_teachers_for_dropdown'),
    # Course Management URLs
    path('dashboard/add-course/', views.add_course, name='add_course'),
    path('dashboard/get-courses/', views.get_courses, name='get_courses'),
    path('dashboard/update-course/<int:course_id>/', views.update_course_status, name='update_course_status'),
    path('dashboard/delete-course/<int:course_id>/', views.delete_course, name='delete_course'),
    # Department Management URLs
    path('dashboard/add-department/', views.add_department, name='add_department'),
    path('dashboard/get-departments/', views.get_departments, name='get_departments'),
    path('dashboard/get-departments-dropdown/', views.get_departments_dropdown, name='get_departments_dropdown'),
    path('dashboard/delete-department/<int:department_id>/', views.delete_department, name='delete_department'),
    # Timetable Management URLs
    path('dashboard/save-timetable/', views.save_timetable, name='save_timetable'),
    path('dashboard/get-timetables/', views.get_timetables, name='get_timetables'),
    path('dashboard/get-timetable-details/', views.get_timetable_details, name='get_timetable_details'),
    path('dashboard/delete-timetable/', views.delete_timetable, name='delete_timetable'),
    # Subject Management URLs
    path('dashboard/get-subjects-dropdown/', views.get_subjects_dropdown, name='get_subjects_dropdown'),
    # Batch Management URLs
    path('dashboard/add-batch/', views.add_batch, name='add_batch'),
    path('dashboard/get-batches/', views.get_batches, name='get_batches'),
    path('dashboard/get-batches-dropdown/', views.get_batches_dropdown, name='get_batches_dropdown'),
    path('dashboard/get-batch-semester/', views.get_batch_current_semester, name='get_batch_current_semester'),
    path('dashboard/delete-batch/<int:batch_id>/', views.delete_batch, name='delete_batch'),
    # Payment Management URLs
    path('dashboard/get-payments/', views.get_payments, name='get_payments'),
    path('dashboard/get-payment-details/<int:payment_id>/', views.get_payment_details, name='get_payment_details'),
    path('dashboard/get-payment-history/<int:payment_id>/', views.get_payment_history, name='get_payment_history'),
    path('dashboard/record-payment/', views.record_payment, name='record_payment'),
    # Library Management URLs
    path('dashboard/add-book/', views.add_book, name='add_book'),
    path('dashboard/get-books-for-library/', library_views.get_books_for_library, name='get_books_for_library'),
    path('dashboard/upload-pdf/', library_views.upload_pdf, name='upload_pdf'),
    path('dashboard/get-pdfs/', library_views.get_pdfs, name='get_pdfs'),
    path('dashboard/get-books-count/', library_views.get_books_count, name='get_books_count'),
    path('dashboard/delete-pdf/', library_views.delete_pdf, name='delete_pdf'),
    path('library/get-books/', views.get_student_books, name='get_student_books'),
    path('library/issue-book/', views.issue_book, name='issue_book'),
    path('library/get-issues/', views.get_student_book_issues, name='get_student_book_issues'),
    path('library/return-book/', views.return_book, name='return_book'),
    # Admin Account Management URLs
    path('dashboard/create-admin/', views.create_admin, name='create_admin'),
    path('dashboard/deactivate-admin/<int:admin_id>/', views.deactivate_admin, name='deactivate_admin'),
    path('dashboard/delete-admin/<int:admin_id>/', views.delete_admin, name='delete_admin'),
    path('dashboard/reset-admin-password/<int:admin_id>/', views.reset_admin_password, name='reset_admin_password'),
    path('dashboard/change-admin-password/', views.change_admin_password, name='change_admin_password'),
    path('dashboard/transfer-primary-role/<int:admin_id>/', views.transfer_primary_role, name='transfer_primary_role'),
    # Subject Assignment URLs
    path('dashboard/get-department-semesters/<int:department_id>/', views.get_department_semesters, name='get_department_semesters'),
    path('dashboard/get-semester-subjects/<int:department_id>/<int:semester_id>/', views.get_semester_subjects, name='get_semester_subjects'),
    path('dashboard/get-subject-teachers/<int:subject_id>/', views.get_subject_teachers, name='get_subject_teachers'),
    path('dashboard/get-department-teachers/<int:department_id>/', views.get_department_teachers, name='get_department_teachers'),
    path('dashboard/get-subject-assignments/', views.get_subject_assignments, name='get_subject_assignments'),
    path('dashboard/remove-subject-assignment/<int:assignment_id>/', views.remove_subject_assignment, name='remove_subject_assignment'),
    path('dashboard/assign-subject/', views.assign_subject, name='assign_subject'),
    # BPUT Scraping URLs
    path('scrape-bput-sessions/', views.scrape_bput_sessions, name='scrape_bput_sessions'),
    path('get-bput-result/', views.get_bput_result, name='get_bput_result'),
    # Quiz URLs
    path('quiz/start/<int:quiz_id>/', views.start_quiz, name='start_quiz'),
    path('quiz/take/<int:attempt_id>/', views.take_quiz, name='take_quiz'),
    path('quiz/results/<int:attempt_id>/', views.quiz_results, name='quiz_results'),
    path('quiz/submit/<int:attempt_id>/', views.submit_quiz, name='submit_quiz'),
    path('quiz/create/', views.create_quiz, name='create_quiz'),
    path('quiz/get-teacher-quizzes/', views.get_teacher_quizzes, name='get_teacher_quizzes'),
    path('quiz/create-question/', views.create_quiz_question, name='create_quiz_question'),
    path('quiz/get-questions/<int:quiz_id>/', views.get_quiz_questions, name='get_quiz_questions'),
    path('quiz/delete-question/<int:question_id>/', views.delete_quiz_question, name='delete_quiz_question'),
    path('quiz/get-responses/<int:quiz_id>/', views.get_quiz_responses, name='get_quiz_responses'),
    path('quiz/get-response-details/<int:attempt_id>/', views.get_response_details, name='get_response_details'),
    path('quiz/publish/<int:quiz_id>/', views.publish_quiz, name='publish_quiz'),
    path('quiz/delete/<int:quiz_id>/', views.delete_quiz, name='delete_quiz'),
]
